services:
  postgresdb:
    image: postgres:16-alpine
    container_name: joblin-db
    env_file:
      - ./apps/db/.env
    ports:
      - "5432:5432"
    # expose:
    #   - "5432"
    volumes:
      - joblin_postgres_data:/var/lib/postgresql/data
    networks:
      - joblin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    build:
      context: ./apps/db
      dockerfile: Dockerfile
    container_name: joblin-migrations
    env_file:
      - ./apps/db/.env
    networks:
      - joblin
    depends_on:
      postgresdb:
        condition: service_healthy

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
      target: base
    container_name: joblin-api
    command: npm run start:dev:poll
    env_file:
      - ./apps/api/.env
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ./apps/api:/home/node/app
    networks:
      - joblin
    depends_on:
      migrations:
        condition: service_completed_successfully

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
      target: base
    container_name: joblin-frontend
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend/src:/home/node/app/src
      - ./apps/frontend/static:/home/node/app/static
      - ./apps/frontend/vite.config.ts:/home/node/app/vite.config.ts:ro
      - ./apps/frontend/svelte.config.js:/home/node/app/svelte.config.js:ro
    networks:
      - joblin

volumes:
  joblin_postgres_data:

networks:
  joblin:
    name: joblin_network
    external: true
