dev:
	podman compose up postgresdb

up:
	POSTGRES_HOST=localhost npm run up

down:
	POSTGRES_HOST=localhost npm run down

new:
	POSTGRES_HOST=localhost npm run new $(name)

status:
	POSTGRES_HOST=localhost npm run status
