import { defineConfig } from 'wxt';

export default defineConfig({
  srcDir: 'src',
  modules: ['@wxt-dev/module-react'],
  manifest: {
    permissions: ['sidePanel', 'tabs', 'storage'],
    host_permissions: ['http://localhost:3001/*'],
    // side_panel.default_path is auto-generated by WXT from
    // src/entrypoints/sidepanel/index.html.
    // key: '<pinned public key>',
    // Uncomment and pin once generated (see chrome://extensions -> Details -> ID
    // after first unpacked load) so the chrome-extension://<id> origin stays
    // stable across `npm run dev` reloads -- required for EXTENSION_ORIGIN in
    // apps/api/.env to keep matching.
  },
});
