// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApplicationStatus string

const (
	ApplicationStatusSentCv     ApplicationStatus = "sent_cv"
	ApplicationStatusFollowedUp ApplicationStatus = "followed_up"
	ApplicationStatusTestTask   ApplicationStatus = "test_task"
	ApplicationStatusInterview  ApplicationStatus = "interview"
	ApplicationStatusReject     ApplicationStatus = "reject"
	ApplicationStatusOffer      ApplicationStatus = "offer"
	ApplicationStatusArchived   ApplicationStatus = "archived"
)

func (e *ApplicationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApplicationStatus(s)
	case string:
		*e = ApplicationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ApplicationStatus: %T", src)
	}
	return nil
}

type NullApplicationStatus struct {
	ApplicationStatus ApplicationStatus
	Valid             bool // Valid is true if ApplicationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApplicationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ApplicationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApplicationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApplicationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApplicationStatus), nil
}

type VacancyStatus string

const (
	VacancyStatusActive  VacancyStatus = "active"
	VacancyStatusExpired VacancyStatus = "expired"
)

func (e *VacancyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VacancyStatus(s)
	case string:
		*e = VacancyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VacancyStatus: %T", src)
	}
	return nil
}

type NullVacancyStatus struct {
	VacancyStatus VacancyStatus
	Valid         bool // Valid is true if VacancyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVacancyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VacancyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VacancyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVacancyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VacancyStatus), nil
}

type Application struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	VacancyID pgtype.UUID
	Status    ApplicationStatus
	Notes     pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	IsRevoked bool
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Vacancy struct {
	ID          pgtype.UUID
	Title       string
	CompanyName string
	Url         pgtype.Text
	Source      pgtype.Text
	Status      VacancyStatus
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
