// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vacancy.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertVacancy = `-- name: UpsertVacancy :exec
INSERT INTO vacancies (title, company_name, url)
VALUES ($1, $2, $3)
ON CONFLICT (url) DO UPDATE
   SET
    title = EXCLUDED.title,
    company_name = EXCLUDED.company_name,
    updated_at = now()
`

type UpsertVacancyParams struct {
	Title       string
	CompanyName string
	Url         pgtype.Text
}

func (q *Queries) UpsertVacancy(ctx context.Context, arg UpsertVacancyParams) error {
	_, err := q.db.Exec(ctx, upsertVacancy, arg.Title, arg.CompanyName, arg.Url)
	return err
}
