services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: joblin-dev-api
    command: npm run start:dev:poll
    environment:
      - .env
      - PORT=3001
    ports:
      - '3001:3001'
    volumes:
      - .:/home/node/app
    networks:
      - primary

networks:
  primary:
    driver: bridge
